# Generated by Django 3.2.7 on 2023-07-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='photo',
        ),
    ]
