# Generated by Django 3.2.7 on 2023-07-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='email',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
