# Generated by Django 3.2.7 on 2023-11-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='admin_name',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
